name: Engauge

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build + Test Stable
    runs-on: ubuntu-latest
    steps:

    - name: Build
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get Coverage
      run:  go get golang.org/x/tools/cmd/cover

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic